# Reference: https://github.com/i3/i3/blob/next/etc/config
start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
default-root-container-layout = 'tiles'
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
after-startup-command = ['exec-and-forget borders']
accordion-padding = 30

exec-on-workspace-change = [
  '/bin/bash',
  '-c',
  'sketchybar --trigger aerospace_workspace_changed FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

on-focus-changed = [
  'move-mouse window-lazy-center',
  'exec-and-forget /bin/bash -c /opt/homebrew/bin/sketchybar --trigger front_app_switched',
  'exec-and-forget sketchybar --trigger update_windows'
]

[gaps]
outer.top = [{ monitor.'^built-in retina display$' = 30 }, 60]
outer.bottom = [{ monitor.'^built-in retina display$' = 10 }, 10]
outer.left = 10
outer.right = 10
inner.horizontal = 10
inner.vertical = 10

[mode.main.binding]
alt-r = 'mode resize'
alt-shift-period = 'mode floating'
alt-shift-semicolon = 'mode service'
alt-enter = '''exec-and-forget osascript -e '
tell application "wezterm"
    activate
end tell'
'''
# Open new finder window
alt-home = '''exec-and-forget osascript -e '
tell application "finder"
    if not (exists Finder window 1) then
        make new Finder window
    end if
    set target of Finder window 1 to home
    activate
end tell'
'''
alt-h = 'exec-and-forget aerospace focus --boundaries-action wrap-around-the-workspace left || /Users/ivan/.config/aerospace/scripts/focus-window.sh left'
alt-j = 'exec-and-forget aerospace focus --boundaries-action wrap-around-the-workspace down || /Users/ivan/.config/aerospace/scripts/focus-window.sh down'
alt-k = 'exec-and-forget aerospace focus --boundaries-action wrap-around-the-workspace up || /Users/ivan/.config/aerospace/scripts/focus-window.sh up'
alt-l = 'exec-and-forget aerospace focus --boundaries-action wrap-around-the-workspace right || /Users/ivan/.config/aerospace/scripts/focus-window.sh right'
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'
alt-ctrl-h = 'join-with left'
alt-ctrl-j = 'join-with down'
alt-ctrl-k = 'join-with up'
alt-ctrl-l = 'join-with right'
alt-f = 'fullscreen'
alt-s = 'layout v_accordion' # 'layout stacking' in i3
alt-w = 'layout h_accordion' # 'layout tabbed' in i3
alt-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3
alt-shift-space = 'layout floating tiling' # 'floating toggle' in i3
alt-1 = 'workspace 1' # development
alt-2 = 'workspace 2' # browser
alt-3 = 'workspace 3' # communication / calendar
alt-4 = 'workspace 4' # beeper
alt-5 = 'workspace 5' # vikunja
alt-6 = 'workspace 6' # config / selfhost
alt-7 = 'workspace 7' # terminal
alt-8 = 'workspace 8' # music
alt-9 = 'workspace 9' # ai assistants
alt-0 = 'workspace 10' # home-assistant
alt-ctrl-1 = 'workspace 11' # timetagger
alt-ctrl-2 = 'workspace 12'
alt-ctrl-3 = 'workspace 13'
alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-0 = 'move-node-to-workspace 10'
alt-ctrl-shift-1 = 'move-node-to-workspace 11'
alt-ctrl-shift-2 = 'move-node-to-workspace 12'
alt-ctrl-shift-3 = 'move-node-to-workspace 13'
shift-h = 'workspace prev'
shift-l = 'workspace next'
ctrl-shift-h = 'move-node-to-workspace prev'
ctrl-shift-l = 'move-node-to-workspace next'
alt-c = 'exec-and-forget /Users/ivan/.config/aerospace/scripts/floating-centered.sh' 

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'

[mode.floating.binding]
alt-c = [
  'exec-and-forget /Users/ivan/.config/aerospace/scripts/floating-centered.sh',
  'mode main'
]
alt-shift-semicolon = 'mode service'
esc = 'mode main'
h = 'exec-and-forget /Users/ivan/.config/aerospace/scripts/move-floating.sh -32 0'
j = 'exec-and-forget /Users/ivan/.config/aerospace/scripts/move-floating.sh 0 32'
k = 'exec-and-forget /Users/ivan/.config/aerospace/scripts/move-floating.sh 0 -32'
l = 'exec-and-forget /Users/ivan/.config/aerospace/scripts/move-floating.sh 32 0'
shift-h = 'exec-and-forget /Users/ivan/.config/aerospace/scripts/resize-floating-centered.sh -128 0'
shift-j = 'exec-and-forget /Users/ivan/.config/aerospace/scripts/resize-floating-centered.sh 0 -128'
shift-k = 'exec-and-forget /Users/ivan/.config/aerospace/scripts/resize-floating-centered.sh 0 128'
shift-l = 'exec-and-forget /Users/ivan/.config/aerospace/scripts/resize-floating-centered.sh 128 0'

[mode.service.binding]
enter = 'reload-config'
esc = 'mode main'
alt-shift-period = 'mode floating'
r = ['layout tiling', 'move up', 'mode main']
alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']

[workspace-to-monitor-force-assignment]
1 = 'main'
2 = 'main'
3 = 'main'
4 = 'main'
5 = 'main'
6 = 'main'
7 = 'main'
8 = 'main'
9 = 'main'
10 = 'main'
11 = ['secondary', 'main']
12 = ['secondary', 'main']
13 = ['secondary', 'main']

# osascript -e 'id of app "<app_name>"'
[[on-window-detected]]
if.app-id = 'com.brave.Browser'
run = ['move-node-to-workspace 1']

[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'md.obsidian'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.insomnia.app'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.github.wez.wezterm'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'org.jeffvli.feishin'
run = ['move-node-to-workspace 8']

[[on-window-detected]]
if.app-id = 'com.automattic.beeper.desktop'
run = ['move-node-to-workspace 4']

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = ['move-node-to-workspace 3']

[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
run = ['move-node-to-workspace 2']

[[on-window-detected]]
if.app-id = 'com.insomnia.app'
run = ['move-node-to-workspace 2']

[[on-window-detected]]
if.app-id = 'com.apple.iCal'
run = ['move-node-to-workspace 3']

[[on-window-detected]]
if.app-id = 'com.brave.Browser.app.haclcbhanpahbkfifjjbbganlanaanfd' # Reactflux (Chrome PWA)
run = ['move-node-to-workspace 1']

[[on-window-detected]]
if.app-id = 'com.brave.Browser.app.jofmikfegijlinjnhbfgmjmfphphpcef' # Home Assistant (Chrome PWA)
run = ['move-node-to-workspace 10']

[[on-window-detected]]
if.app-id = 'com.apple.mail'
run = ['move-node-to-workspace 3']

[[on-window-detected]]
if.app-id = 'com.openai.chat'
run = ['move-node-to-workspace 9']

[[on-window-detected]]
if.app-id = 'com.kangfenmao.CherryStudio'
run = ['move-node-to-workspace 9']

[[on-window-detected]]
if.app-id = 'com.brave.Browser.app.bkpkohmifefkicambcnmkfcikdpppmhi' # TimeTagger (Chrome PWA)
run = ['move-node-to-workspace 11']

[[on-window-detected]]
if.app-id = 'com.brave.Browser.app.joldddnjngacnbjpifgcpceolhcgfdkb' # Beaver (Chrome PWA)
run = ['move-node-to-workspace 11']

[[on-window-detected]]
if.window-title-regex-substring = 'nas'
run = ['move-node-to-workspace 6']

[[on-window-detected]]
if.window-title-regex-substring = 'selfhost'
run = ['move-node-to-workspace 6']

[[on-window-detected]]
if.window-title-regex-substring = '.config'
run = ['move-node-to-workspace 6']

[[on-window-detected]]
if.app-id = 'com.brave.Browser.app.ppbijedchfccpkokmbgcdhkbmcnoagof'
run = ['move-node-to-workspace 5']

[[on-window-detected]]
if.app-id = 'com.github.wez.wezterm'
run = ['move-node-to-workspace 7']